/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.inversedynamics;

public final class JointType {
  public static final int FIXED = 0;
  public static final int REVOLUTE = FIXED + 1;
  public static final int PRISMATIC = REVOLUTE + 1;
  public static final int FLOATING = PRISMATIC + 1;
}
