/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.softbody;

public final class btSoftJointBodyType {
  public static final int BT_JOINT_SOFT_BODY_CLUSTER = 1;
  public static final int BT_JOINT_RIGID_BODY = BT_JOINT_SOFT_BODY_CLUSTER + 1;
  public static final int BT_JOINT_COLLISION_OBJECT = BT_JOINT_RIGID_BODY + 1;
}
