/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.linearmath;

public interface LinearMathConstants {
	public static final int BT_BULLET_VERSION = 287;
	public static final double BT_LARGE_FLOAT = 1e18;
	public static final double BT_ONE = 1.0;
	public static final double BT_ZERO = 0.0;
	public static final double BT_TWO = 2.0;
	public static final double BT_HALF = 0.5;
	public static final String btVector3DataName = "btVector3FloatData";
	public static final String btQuaternionDataName = "btQuaternionFloatData";
	public static final int USE_BANCHLESS = 1;
	public static final int USE_BT_CLOCK = 1;
	public static final int BT_USE_PLACEMENT_NEW = 1;
	public static final int BT_HEADER_LENGTH = 12;
}
