/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

public final class BroadphaseNativeTypes {
	public static final int BOX_SHAPE_PROXYTYPE = 0;
	public static final int TRIANGLE_SHAPE_PROXYTYPE = BOX_SHAPE_PROXYTYPE + 1;
	public static final int TETRAHEDRAL_SHAPE_PROXYTYPE = TRIANGLE_SHAPE_PROXYTYPE + 1;
	public static final int CONVEX_TRIANGLEMESH_SHAPE_PROXYTYPE = TETRAHEDRAL_SHAPE_PROXYTYPE + 1;
	public static final int CONVEX_HULL_SHAPE_PROXYTYPE = CONVEX_TRIANGLEMESH_SHAPE_PROXYTYPE + 1;
	public static final int CONVEX_POINT_CLOUD_SHAPE_PROXYTYPE = CONVEX_HULL_SHAPE_PROXYTYPE + 1;
	public static final int CUSTOM_POLYHEDRAL_SHAPE_TYPE = CONVEX_POINT_CLOUD_SHAPE_PROXYTYPE + 1;
	public static final int IMPLICIT_CONVEX_SHAPES_START_HERE = CUSTOM_POLYHEDRAL_SHAPE_TYPE + 1;
	public static final int SPHERE_SHAPE_PROXYTYPE = IMPLICIT_CONVEX_SHAPES_START_HERE + 1;
	public static final int MULTI_SPHERE_SHAPE_PROXYTYPE = SPHERE_SHAPE_PROXYTYPE + 1;
	public static final int CAPSULE_SHAPE_PROXYTYPE = MULTI_SPHERE_SHAPE_PROXYTYPE + 1;
	public static final int CONE_SHAPE_PROXYTYPE = CAPSULE_SHAPE_PROXYTYPE + 1;
	public static final int CONVEX_SHAPE_PROXYTYPE = CONE_SHAPE_PROXYTYPE + 1;
	public static final int CYLINDER_SHAPE_PROXYTYPE = CONVEX_SHAPE_PROXYTYPE + 1;
	public static final int UNIFORM_SCALING_SHAPE_PROXYTYPE = CYLINDER_SHAPE_PROXYTYPE + 1;
	public static final int MINKOWSKI_SUM_SHAPE_PROXYTYPE = UNIFORM_SCALING_SHAPE_PROXYTYPE + 1;
	public static final int MINKOWSKI_DIFFERENCE_SHAPE_PROXYTYPE = MINKOWSKI_SUM_SHAPE_PROXYTYPE + 1;
	public static final int BOX_2D_SHAPE_PROXYTYPE = MINKOWSKI_DIFFERENCE_SHAPE_PROXYTYPE + 1;
	public static final int CONVEX_2D_SHAPE_PROXYTYPE = BOX_2D_SHAPE_PROXYTYPE + 1;
	public static final int CUSTOM_CONVEX_SHAPE_TYPE = CONVEX_2D_SHAPE_PROXYTYPE + 1;
	public static final int CONCAVE_SHAPES_START_HERE = CUSTOM_CONVEX_SHAPE_TYPE + 1;
	public static final int TRIANGLE_MESH_SHAPE_PROXYTYPE = CONCAVE_SHAPES_START_HERE + 1;
	public static final int SCALED_TRIANGLE_MESH_SHAPE_PROXYTYPE = TRIANGLE_MESH_SHAPE_PROXYTYPE + 1;
	public static final int FAST_CONCAVE_MESH_PROXYTYPE = SCALED_TRIANGLE_MESH_SHAPE_PROXYTYPE + 1;
	public static final int TERRAIN_SHAPE_PROXYTYPE = FAST_CONCAVE_MESH_PROXYTYPE + 1;
	public static final int GIMPACT_SHAPE_PROXYTYPE = TERRAIN_SHAPE_PROXYTYPE + 1;
	public static final int MULTIMATERIAL_TRIANGLE_MESH_PROXYTYPE = GIMPACT_SHAPE_PROXYTYPE + 1;
	public static final int EMPTY_SHAPE_PROXYTYPE = MULTIMATERIAL_TRIANGLE_MESH_PROXYTYPE + 1;
	public static final int STATIC_PLANE_PROXYTYPE = EMPTY_SHAPE_PROXYTYPE + 1;
	public static final int CUSTOM_CONCAVE_SHAPE_TYPE = STATIC_PLANE_PROXYTYPE + 1;
	public static final int CONCAVE_SHAPES_END_HERE = CUSTOM_CONCAVE_SHAPE_TYPE + 1;
	public static final int COMPOUND_SHAPE_PROXYTYPE = CONCAVE_SHAPES_END_HERE + 1;
	public static final int SOFTBODY_SHAPE_PROXYTYPE = COMPOUND_SHAPE_PROXYTYPE + 1;
	public static final int HFFLUID_SHAPE_PROXYTYPE = SOFTBODY_SHAPE_PROXYTYPE + 1;
	public static final int HFFLUID_BUOYANT_CONVEX_SHAPE_PROXYTYPE = HFFLUID_SHAPE_PROXYTYPE + 1;
	public static final int INVALID_SHAPE_PROXYTYPE = HFFLUID_BUOYANT_CONVEX_SHAPE_PROXYTYPE + 1;
	public static final int MAX_BROADPHASE_COLLISION_TYPES = INVALID_SHAPE_PROXYTYPE + 1;
}
