/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

public final class ContactCallbackEvent {
	public static final int TYPE_MASK = 0x0F;
	public static final int BY_MASK = 12;
	public static final int FILTERED = 1;
	public static final int INCLUDE_POINT = 2;
	public static final int BY_WRAPPER = 4;
	public static final int BY_MANIFOLD = 4;
	public static final int BY_OBJECT = 8;
	public static final int BY_VALUE = 12;
	public static final int SHIFT_ON_ADDED = 0;
	public static final int SHIFT_ON_PROCESSED = 4;
	public static final int SHIFT_ON_DESTROYED = 8;
	public static final int SHIFT_ON_STARTED = 12;
	public static final int SHIFT_ON_ENDED = 16;
	public static final int ON_ADDED_UNFILTERED_WRAPPER = (BY_WRAPPER) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_UNFILTERED_OBJECT = (BY_OBJECT) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_UNFILTERED_VALUE = (BY_VALUE) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_UNFILTERED_WRAPPER_INCLUDEPOINT = (BY_WRAPPER | INCLUDE_POINT) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_UNFILTERED_OBJECT_INCLUDEPOINT = (BY_OBJECT | INCLUDE_POINT) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_UNFILTERED_VALUE_INCLUDEPOINT = (BY_VALUE | INCLUDE_POINT) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_FILTERED_WRAPPER = (FILTERED | BY_WRAPPER) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_FILTERED_OBJECT = (FILTERED | BY_OBJECT) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_FILTERED_VALUE = (FILTERED | BY_VALUE) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_FILTERED_WRAPPER_INCLUDEPOINT = (FILTERED | BY_WRAPPER | INCLUDE_POINT) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_FILTERED_OBJECT_INCLUDEPOINT = (FILTERED | BY_OBJECT | INCLUDE_POINT) << SHIFT_ON_ADDED;
	public static final int ON_ADDED_FILTERED_VALUE_INCLUDEPOINT = (FILTERED | BY_VALUE | INCLUDE_POINT) << SHIFT_ON_ADDED;
	public static final int ON_PROCESSED_UNFILTERED_OBJECT = (BY_OBJECT) << SHIFT_ON_PROCESSED;
	public static final int ON_PROCESSED_UNFILTERED_VALUE = (BY_VALUE) << SHIFT_ON_PROCESSED;
	public static final int ON_PROCESSED_UNFILTERED_OBJECT_INCLUDEPOINT = (BY_OBJECT | INCLUDE_POINT) << SHIFT_ON_PROCESSED;
	public static final int ON_PROCESSED_UNFILTERED_VALUE_INCLUDEPOINT = (BY_VALUE | INCLUDE_POINT) << SHIFT_ON_PROCESSED;
	public static final int ON_PROCESSED_FILTERED_OBJECT = (FILTERED | BY_OBJECT) << SHIFT_ON_PROCESSED;
	public static final int ON_PROCESSED_FILTERED_VALUE = (FILTERED | BY_VALUE) << SHIFT_ON_PROCESSED;
	public static final int ON_PROCESSED_FILTERED_OBJECT_INCLUDEPOINT = (FILTERED | BY_OBJECT
		| INCLUDE_POINT) << SHIFT_ON_PROCESSED;
	public static final int ON_PROCESSED_FILTERED_VALUE_INCLUDEPOINT = (FILTERED | BY_VALUE | INCLUDE_POINT) << SHIFT_ON_PROCESSED;
	public static final int ON_DESTROYED = BY_VALUE << SHIFT_ON_DESTROYED;
	public static final int ON_STARTED_UNFILTERED_MANIFOLD = (BY_MANIFOLD) << SHIFT_ON_STARTED;
	public static final int ON_STARTED_UNFILTERED_OBJECT = (BY_OBJECT) << SHIFT_ON_STARTED;
	public static final int ON_STARTED_UNFILTERED_VALUE = (BY_VALUE) << SHIFT_ON_STARTED;
	public static final int ON_STARTED_FILTERED_MANIFOLD = (FILTERED | BY_MANIFOLD) << SHIFT_ON_STARTED;
	public static final int ON_STARTED_FILTERED_OBJECT = (FILTERED | BY_OBJECT) << SHIFT_ON_STARTED;
	public static final int ON_STARTED_FILTERED_VALUE = (FILTERED | BY_VALUE) << SHIFT_ON_STARTED;
	public static final int ON_ENDED_UNFILTERED_MANIFOLD = (BY_MANIFOLD) << SHIFT_ON_ENDED;
	public static final int ON_ENDED_UNFILTERED_OBJECT = (BY_OBJECT) << SHIFT_ON_ENDED;
	public static final int ON_ENDED_UNFILTERED_VALUE = (BY_VALUE) << SHIFT_ON_ENDED;
	public static final int ON_ENDED_FILTERED_MANIFOLD = (FILTERED | BY_MANIFOLD) << SHIFT_ON_ENDED;
	public static final int ON_ENDED_FILTERED_OBJECT = (FILTERED | BY_OBJECT) << SHIFT_ON_ENDED;
	public static final int ON_ENDED_FILTERED_VALUE = (FILTERED | BY_VALUE) << SHIFT_ON_ENDED;
}
