/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

public final class eEpaStatus {
	public static final int eEpaValid = 0;
	public static final int eEpaTouching = eEpaValid + 1;
	public static final int eEpaDegenerated = eEpaTouching + 1;
	public static final int eEpaNonConvex = eEpaDegenerated + 1;
	public static final int eEpaInvalidHull = eEpaNonConvex + 1;
	public static final int eEpaOutOfFaces = eEpaInvalidHull + 1;
	public static final int eEpaOutOfVertices = eEpaOutOfFaces + 1;
	public static final int eEpaAccuraryReached = eEpaOutOfVertices + 1;
	public static final int eEpaFallBack = eEpaAccuraryReached + 1;
	public static final int eEpaFailed = eEpaFallBack + 1;
}
