/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

public final class eGjkStatus {
	public static final int eGjkValid = 0;
	public static final int eGjkInside = eGjkValid + 1;
	public static final int eGjkFailed = eGjkInside + 1;
}
