/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

public final class PHY_ScalarType {
  public static final int PHY_FLOAT = 0;
  public static final int PHY_DOUBLE = PHY_FLOAT + 1;
  public static final int PHY_INTEGER = PHY_DOUBLE + 1;
  public static final int PHY_SHORT = PHY_INTEGER + 1;
  public static final int PHY_FIXEDPOINT88 = PHY_SHORT + 1;
  public static final int PHY_UCHAR = PHY_FIXEDPOINT88 + 1;
}
